#%RAML 1.0
title: American Fligts API

/flights:
  get:
    queryParameters:
      destinations:
        required: false
        enum:
          - SFO
          - LAX
          - CLE

  post:



  /{ID}:
    get:
      